version: '3'
services:
  trafficlights:
    image: com.droy/traffic-lights
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://trafficlights_db:3306/trafficlights
      - SPRING_DATASOURCE_USERNAME=traffic
      - SPRING_DATASOURCE_PASSWORD=test
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.jdbc.Driver
    networks:
      - localBridge

  trafficlights_db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=trafficlights
      - MYSQL_USER=traffic
      - MYSQL_PASSWORD=test
    networks:
      - localBridge

networks:
  localBridge: